# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  # - override hydra_logging: colorlog
  - override hydra_logging: disabled 
  - override job_logging: disabled

# output directory, generated dynamically on each run
run:
  dir: ${paths.run_dir}
sweep:
  dir: ${paths.sweep_run_dir}
  subdir: ${hydra.job.num}
