# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
# root_dir: ${oc.env:PROJECT_ROOT}
root_dir: "hydra_tests"

run_dir: ${paths.root_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep_run_dir: ${paths.root_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}

# path to data directory
# data_dir: ${paths.root_dir}/data/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to logging directory
# log_dir: ${paths.run_dir}/logs/
log_dir: ${paths.output_dir}/logs/

# checkpoint dir
# checkpoint_dir: ${paths.run_dir}/checkpoints/
checkpoint_dir: ${paths.output_dir}/checkpoints/

# path to working directory
work_dir: ${hydra:runtime.cwd}
