hidden_size: [32, 64]
n_hidden_layers: [2, 3, 4]
dropout: [0.0, 0.1, 0.2]

optimizer: ['adam']
lr: [0.5e-3]

patience: [5]
factor: [0.02]
min_lr: [1.0e-6]
clip: [0.01, 0.1, 0.5, 1, 2, 10]

batch_size: [[1000, 1000, 4096]]
