name: Test / Deploy

# Run on all PR's and on pushes/merges to deploy and master
on:
  # pull_request:
  #   branches: ['master', '!paper.md']
  push:
    # branches: ['master', '!paper.md']
    tags: ["v*"]

jobs:

  check_semantic_version_placeholder:
    name: Check semantic version placeholder exists in the __init__

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Check lines exist
      run: |
        grep -x "__version__ = ...  # semantic-version-placeholder" crescendo/__init__.py

  build_and_publish:
    # This workflow follows the best practices outlined here:
    # https://github.com/marketplace/actions/pypi-publish
    # for deploying a project to PyPI via a GH action. It only runs on tags

    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/crescendo/
    permissions:
      id-token: write

    needs:
      - check_semantic_version_placeholder

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and apply version
      run: bash scripts/build_project.sh

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/
